source 'http://rubygems.org'

gem "sinatra"
gem "data_mapper"

group :development, :test do
  gem 'sqlite3'
  gem "dm-sqlite-adapter"
end

group :production do
  gem 'pg'
  gem 'dm-postgres-adapter'
end